services:
  front:
    # Dockerfileがある場所を指定
    build: ./front
    # image: vue3:3.10.1
    container_name: front
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
